spring:
  application:
    name: playerAPI

  datasource:
#    JDBC Java Database Connectivity
    url: "jdbc:postgresql://localhost:5200/korfball"
    username: "richard"
    password: "#FuckYourMum2020"

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  data:
    jdbc:
      dialect: postgresql

server:
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"


