name: CI - Build Backend

# on is the section of what should trigger the workflow.
# The workflow will only trigger, when a pull request is made to main branch and the files in backend and sub
# directories have been changed
on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/*

# defines the tasks or jobs that your workflow will perform
# an independent task in my workflow
jobs:
  # a name we have used to define our job
  ci-build:
    # runs on specifies the runner environment for your job, you have used ubuntu-latest which is standard for most workflows
    runs-on: ubuntu-latest

    # this is where you set up a postgres database
    # Services are containers that run alongside your workflow
    # they provide resources, the run alongside your work flow simulating a production like environment
    services:
      # when you define the postgres service in your work flow, you spin up a container with the specified image
      # you configure it via the env variable
      # the ports map the internal postgres port, to a port accessible from the job runner
      # your backend code connects to this database
      # how does your backend connect -> your backend likely uses a configuration file application.yml
      # during which the details match it jdbc:postgresql://localost:5200/korfball
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: "#FuckYourMum2020"
          POSTGRES_USER: richard
          POSTGRES_DB: korfball
        ports:
          - 5200:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # Set default behaviour for all run commands in the job
    # control the execution context of a job
    # this means all run steps in the build job will execute in the ./backend directory
    defaults:
      run:
        working-directory: ./backend

    steps:
      # checks out the code from the pull request
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Build and run tests with Maven
        run: mvn -ntp -B package -DskipTests

