name: CD - Build Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/**
  pull_request:
    branches:
      - main
    types:
      - closed  # This ensures the workflow triggers when a pull request is closed (merged or otherwise).

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: "#FuckYourMum2020"
          POSTGRES_USER: richard
          POSTGRES_DB: korfball
        ports:
          - 5200:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./backend

    steps:

      - name: slack webhook call
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PLAYERAPI }}
        working-directory: ${{ github.workspace }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Continuous Deployment!"}' $SLACK_WEBHOOK
          

      - uses: actions/checkout@v3


      - name: slack webhook call
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PLAYERAPI }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment: checked out the code!"}' $SLACK_WEBHOOK

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: 'maven'
          distribution: temurin

      - name: slack webhook call
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PLAYERAPI }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment: Set up the Java in the environment out the code!"}' $SLACK_WEBHOOK

      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: slack webhook call
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PLAYERAPI }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment: Logged into docker!"}' $SLACK_WEBHOOK

      - name: Generate Random Build Number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT

      - name: slack webhook call
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PLAYERAPI }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment: generating the build number!"}' $SLACK_WEBHOOK

      - name: Wait for Postgres to be Ready
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5200; then
              echo "Postgres is ready";
              exit 0;
            fi;
            echo "Waiting for Postgres...";
            sleep 5;
          done;
          echo "Postgres did not become ready in time";
          exit 1;

      - name: Build Package with Maven
        run: mvn -ntp -B verify  -DskipTests  -Ddocker.image.tag=${{steps.build-number.outputs.BUILD_NUMBER}} jib:build

      - name: slack webhook call
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PLAYERAPI }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment: built the project and run the tests!"}' $SLACK_WEBHOOK

      - name: Update Dockerrun.aws.json with New Tag
        run: |
          echo "Before updating tag"
          cat Dockerrun.aws.json
          sed -i -E 's_(rsmithuchot1/player-api:)([^"]*)_\1'${{steps.build-number.outputs.BUILD_NUMBER}}'_' Dockerrun.aws.json
          echo "After updating tag"
          cat Dockerrun.aws.json

      - name: slack webhook call
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PLAYERAPI }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment: Created a new build number!"}' $SLACK_WEBHOOK
          
              

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: ${{ github.SHA }}
          region: ${{ secrets.EB_REGION }}
          deployment_package: backend/Dockerrun.aws.json

      - name: slack webhook call
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PLAYERAPI }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment: deployed to elastic bean stalk!"}' $SLACK_WEBHOOK
        

      - name: creating a branch to push Dockerrun.aws.json changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b update-dockerrun-${{ steps.build-number.outputs.BUILD_NUMBER }}
          git add Dockerrun.aws.json
          git commit -m "Update Dockerrun.aws.json docker image with new tag ${{ steps.build-number.outputs.BUILD_NUMBER }}"
          git push origin update-dockerrun-${{ steps.build-number.outputs.BUILD_NUMBER }}


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-dockerrun-${{ steps.build-number.outputs.BUILD_NUMBER }}
          title: "Update Dockerrun.aws.json"
          body: "This PR updates the Docker image tag in Dockerrun.aws.json to ${{ steps.build-number.outputs.BUILD_NUMBER }}"
          base: main
          labels: ["automation"]
          merge: true
          merge-method: squash
          

#      - name: Commit and push Dockerrun.aws.json
#        run: |
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          git add .
#          git commit -m "Update Dockerrun.aws.json docker image with new tag ${{ steps.build-number.outputs.BUILD_NUMBER }}"
#          git push

      - name: slack webhook call
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PLAYERAPI }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment: adding the new docker run to my git, though a push!"}' $SLACK_WEBHOOK